config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq' if Rails.env.development?
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'posts#index'

  resources :accounts, only: [:show] do
    resources :follows, only: [:create]
    resources :unfollows, only: [:create]
    resources :followings, only: [:index]
    resources :followers, only: [:index]
  end

  resource :profile, only: [:show, :edit,  :update]


  resources :posts, only: [:index, :show, :new, :create, :edit, :update, :destroy] do

    resource :like, only: [:show, :create, :destroy]
    resources :comments, only: [:index, :create, :destroy]
  end

  resource :timeline, only: [:show]
  resource :timelinelike, only: [:show]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, presence: true

  belongs_to :post
  belongs_to :user
  
end

app/models/like.rb
class Like < ApplicationRecord

  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  
  validates :content, presence: true

  has_many_attached :images
  
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  belongs_to :user

end

app/models/profile.rb
class Profile < ApplicationRecord
  
  belongs_to :user
  has_one_attached :avatar
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :following, class_name: 'User'
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :profile, dependent: :destroy
  

  has_many :following_relationships, foreign_key: 'follower_id', class_name: 'Relationship', dependent: :destroy
  has_many :followings, through: :following_relationships, source: :following


  has_many :follower_relationships, foreign_key: 'following_id', class_name: 'Relationship', dependent: :destroy
  has_many :followers, through: :follower_relationships, source: :follower


  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy

  def prepare_profile
    profile || build_profile
  end

  def hasliked?(post)
    likes.exists?(post_id: post.id)
  end

  def avatar_image
    if profile&.avatar&.attached?
      profile.avatar
    else
      'Ellipse.png'
    end
  end

  def has_followed?(user)
    following_relationships.exists?(following_id: user.id)
  end

  def follow!(user)
   
    user_id = get_user_id(user)

    following_relationships.create(following_id: user_id)
  end

  def unfollow!(user)
    user_id = get_user_id(user)

    relation = following_relationships.find_by!(following_id: user_id)
    relation.destroy!
  end

  def following_count
    followings.count
  end

  def follower_count
    followers.count
  end

  private
  def get_user_id(user)
    if user.is_a?(User)
      user.id
    else
      user
    end
  end


end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController 

  def show
    @user = User.find(params[:id])
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [ :username, :email, :password, :password_confirmation, :avatar　]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
    devise_parameter_sanitizer.permit :sign_in, keys: added_attrs
    devise_parameter_sanitizer.permit(:account_update, keys: [ :avatar])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController 

  def index
    post = Post.find(params[:post_id])
    comments = post.comments
    render json: comments, include: { user: [ :profile] }
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(comment_params)
    @comment.user_id = current_user.id
    comment_reply
    render json: @comment, include: { user: [ :profile] }
  end

  private
  def comment_params
    params.require(:comment).permit(:content).merge(user_id: current_user.id)
  end

  def comment_reply
    users = User.all
    users.each do |user|
      @to_name = user.username
      @from_name = @comment.user
      if @comment.content.include?("@#{@to_name}")
        @content = @comment.content
        CommentMailer.comment_reply(user, @from_name, @content).deliver_later
        @comment.save!
      else
        @comment.save!
      end
    end

  end

end

app/controllers/followers_controller.rb
class FollowersController < ApplicationController 
  def index
    @user = User.find(params[:account_id])
    @followers = @user.followers
  end
end

app/controllers/followings_controller.rb
class FollowingsController < ApplicationController
  def index
    @user = User.find(params[:account_id])
    @followings = @user.followings
  end 
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController 
  before_action :authenticate_user!
  def create
    current_user.follow!(params[:account_id])
    redirect_to account_path(params[:account_id])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!

  def show
    post = Post.find(params[:post_id])
    like_status = current_user.hasliked?(post)
    render json: { hasLiked: like_status }
  end

  def create

    post = Post.find(params[:post_id])
    post.likes.create!(user_id: current_user.id)

    render json: { status: 'ok' }
  end

  def destroy
    post = Post.find(params[:post_id])
    like = post.likes.find_by!(user_id: current_user.id)
    like.destroy!
    
    render json: { status: 'ok'}
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController 
  before_action :authenticate_user!, only: [:new, :create]

  def index
    @posts = Post.all.order(created_at: :desc)
  end

  def show
    @post = Post.find(params[:id])
    @comment = @post.comments.build

    @comments = @post.comments
  end

  def new 
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save!
      redirect_to posts_path, notice: '投稿できました'
    else
      flash.now[:error] = '投稿できませんでした'
      render :new
    end
  end

  def destroy
    post = current_user.posts.find(params[:id])
    post.destroy!
    redirect_to posts_path, notice: '削除に成功しました'
  end

  private
  def post_params
    params.require(:post).permit(:content, images: [])
  end


end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController 

  def show
    @user = current_user
    @profile = current_user.prepare_profile
  end

  def update
    @profile = current_user.prepare_profile
    @profile.id = current_user.id
    @profile.assign_attributes(profile_params)
    if @profile.save
      redirect_to profile_path, notice: '更新できました'
    else
      flash.now[:error] = '更新できませんでした'
      render :show
    end

  end

  private
  def profile_params
    params.require(:profile).permit(:avatar)
  end

end

app/controllers/timelinelikes_controller.rb
class TimelinelikesController < ApplicationController 
  def show
    @posts = Post.left_outer_joins(:likes).group('posts.id').select('posts.*, COUNT(likes.*) AS likes_count').distinct.reorder(likes_count: :desc).limit(5)
  end
end

app/controllers/timelines_controller.rb
class TimelinesController < ApplicationController 
  before_action :authenticate_user!

  def show
    user_ids = current_user.followings.pluck(:id)
    @posts = Post.where(user_id: user_ids).order(created_at: :desc)
  end

end

app/controllers/unfollows_controller.rb
class UnfollowsController < ApplicationController 
  before_action :authenticate_user!

  def create
    current_user.unfollow!(params[:account_id])
    redirect_to account_path(params[:account_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/accounts/show.html.haml
.container
  .account_header
    .back_icon
      = link_to image_tag('矢印.png'), :back
    
    .follow_btn
      - if user_signed_in?
        - if current_user&.has_followed?(@user)
          = link_to 'Unfollow', account_unfollows_path(@user), data: {method: 'post'}, class: 'follow_btn'
        - else
          = link_to 'Follow', account_follows_path(@user), data: {method: 'post'}, class: 'follow_btn'
  .account_username
    = @user.username
  .acount_avatar
    = image_tag @user.avatar_image, class: 'profile_usericon'
    
  .account_status
    .post_count
      .figure-1
        %p= @user.posts.count
      %p.status-text Posts
    .following_count
      = link_to account_followings_path(@user) do
        .figure-2
          %p= @user.following_count
        %p.status-text following
    .follower_count
      = link_to account_followers_path(@user) do
        .figure-3
          %p= @user.follower_count
        %p.status-text Followers

  .img-container-top
    - @user.posts.each do |post|
      - post.images.each do |image|
        .img-container
          = image_tag image, class: 'box'
  = link_to 'TOP', root_path, class: 'link_to_top'

app/views/commons/_images.html.haml
- if post.images.attached?
  - if post.images.size == 3
    .grid-img
      .grid-img-one#itema
        = image_tag post.images.first, class: 'img'
      .grid-img-two#itemb
        = image_tag post.images.second, class: 'img'
      .grid-img-third#itemc
        = image_tag post.images.third, class: 'img' 
  - elsif post.images.size == 2
    .display-flex
      .display-flex-left
        = image_tag post.images.first, class: 'flex-img'
      .display-flex-right
        = image_tag post.images.second, class: 'flex-img'
  - else 
    .image-one-box
      = image_tag post.images.first, class: 'image-first'

app/views/commons/_posts.html.haml
.post_container
  - @posts.each do |post|
    .post#post-index{data:{post_id: post.id}}
      .avatar
        - if user_signed_in?
          - if post.user_id == current_user.id
            = link_to profile_path do
              = image_tag post.user.avatar_image, class: 'usericon'
          - else
            = link_to account_path(post.user) do
              = image_tag post.user.avatar_image, class: 'usericon'
        - else
          = link_to account_path(post.user) do
            = image_tag post.user.avatar_image, class: 'usericon'

      .post_user
        = post.user.username
      .post_time
        %time(datetime="#{post.created_at}")= time_ago_in_words(post.created_at)
      = render '/commons/images', post: post

      .delete
        - if user_signed_in?
          -if current_user.id == post.user_id
            = link_to '削除する', post_path(post.id), data:{method: 'delete', confirm: '本当に削除してもよろしいですか'}, class: 'delete_btn '
      .icon_container
        .like 
          - if user_signed_in?
            - if current_user.hasliked?(post)
              .article_heart.active-heart{class: "#{post.id}" , id: "#{post.id}"}
                = image_tag('ハート赤.png')
              .article_heart.hidden.inactive-heart{class: "#{post.id}", id: "#{post.id}"}
                = image_tag('ハート.png')
            - else
              .article_heart.inactive-heart{class: "#{post.id}" , id: "#{post.id}"}
                = image_tag('ハート.png')
              .article_heart.hidden.active-heart{class: "#{post.id}" , id: "#{post.id}"}
                = image_tag('ハート赤.png')
        .comment
          = link_to image_tag('コメント.png'), post_path(post.id), class: 'icon_button'
        .share
          = link_to image_tag('共有.png'), "https://twitter.com/share?url=#{request.url}",title: 'Twitter', target: '_blank', class: 'icon_button '
        
      .post_content
        = post.content 
       

app/views/followers/index.html.haml
.container
  .follow-header
    .follow_back_icon
      = link_to image_tag('矢印.png'), :back
  %p.follow_title FOLLOWERS
  - @followers.each do |follower|
    .follow_list
      = image_tag follower.avatar_image, class: 'follow_usericon'
      .follow_name
        %p= follower.username
  = link_to 'TOP', root_path, class: 'link_to_top'
  

app/views/followings/index.html.haml
.container
  .follow-header
    .follow_back_icon
      = link_to image_tag('矢印.png'), :back
  %p.follow_title FOLLOWINGS
  - @followings.each do |following|
    .follow_list
      .follow_icon
        = image_tag following.avatar_image, class: 'follow_usericon'
      .follow_name
        %p= following.username
        
  = link_to 'TOP', root_path, class: 'link_to_top'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title PhotoPostingApp
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
  %body
    .container
      - if flash[:notice]
        .flash_message
          %p.notice= notice
      - if flash[:alert]
        .flash_message
          %p.alert= alert     
    = yield

app/views/posts/index.html.haml
.container 
  .camera
    = link_to image_tag('カメラ.png'), new_post_path , class: 'camera_icon'
  .timeline_title
    %p ALL POSTS
  .timeline_container
  = render 'commons/posts'

 
  = link_to '人気投稿一覧へ', timelinelike_path, class: 'devise_link'
  %br
  = link_to 'フォローしているアカウントの投稿一覧へ', timeline_path , class: 'devise_link'
  %br

  - if user_signed_in?
    = link_to 'ログアウト', destroy_user_session_path, class: 'devise_link link_login'
  - else 
    = link_to 'ログイン', new_user_session_path, class: 'devise_link link_login'

app/views/posts/new.html.haml
.container
  = form_with model: @post do |f|
    .post_new_header
      %div
        = link_to 'Cance', :back , class: 'cance_button'
      %div
        %p.status_button STATUS
      %div
        = f.submit 'POST', class: 'post_new_button'
    .usericon
      = image_tag current_user.avatar_image, class: 'usericon'
    .post_username
      %p= current_user.username
    %div 
      = f.text_field :content, placeholder: "What's on your mind ?", class: 'post_content_form'
    %div 
    
      = f.label :images, "+ Album", class: 'images_input_btn' do
        %i.images_form_name + Album
        = f.file_field :images, multiple: true, class: 'images_form'
    = link_to 'TOP', root_path, class: 'link_to_top'

app/views/posts/show.html.haml
.container
  .comment_header
    .comment_back_icon
      = link_to image_tag('矢印.png'), :back
  %p.comment_title COMMENT
    
  .comment#post-show{data:{post_id: @post.id}}
    
  .comments-container

  .comment-set
    - if user_signed_in?
      .comment-text-area
        = text_area_tag :comment_content, '', class: 'sm w-100',size: '1x1'
      .btn-secondary.btn.w-100.add-comment-btn
        Comment
  = link_to 'TOP', root_path, class: 'link_to_top'

app/views/profiles/edit.html.haml
= form_with(model: @profile, url: profile_path, method: 'put', local: true ) do |f|
  %div
    = f.file_field :avatar 
  %div
    = f.submit 'Submit', class: 'btn btn-outline-secondary'

app/views/profiles/show.html.haml
.container 
  .profile_header
    .profile_back_icon
      = link_to image_tag('矢印.png'), :back
    .profile_username
      = current_user.username

  .avatar
    - if current_user.profile&.avatar&.attached?
      = image_tag @user.profile.avatar, class: 'profile_usericon'
    - else 
      = image_tag 'Ellipse.png', class: 'profile_usericon'

  .avatar_edit_form.hidden
    = form_with(model: @profile, url: profile_path, method: 'put', local: true ) do |f|
      %div
        = f.label :avatar, '画像を選択', class: 'aaa' do
          %i.images_form_avatar Select your avatar
          = f.file_field :avatar, class: 'images_form'
      %div
        = f.submit 'SUBMIT', class: 'avatar_submit_btn'

  .account_status
    .post_count
      .figure-1
        %p= @user.posts.count
      %p.status-text Posts
    .following_count
      = link_to account_followings_path(@user) do
        .figure-2
          %p= @user.following_count
        %p.status-text following
    .follower_count
      = link_to account_followers_path(@user) do
        .figure-3
          %p= @user.follower_count
        %p.status-text Followers

  .img-container-top
    - @user.posts.each do |post|
      - post.images.each do |image|
        .img-container
          = image_tag image, class: 'box'
  = link_to 'TOP', root_path, class: 'link_to_top'

app/views/timelinelikes/show.html.haml
.container
  .camera
    = link_to image_tag('カメラ.png'), new_post_path , class: 'camera_icon'
  .timeline_title
    %p POPULAR POSTS
  .timeline_container
  = render 'commons/posts'

  = link_to '全ての投稿一覧へ', posts_path, class: 'devise_link'
  %br
  = link_to 'フォローしているアカウントの投稿一覧へ', timeline_path , class: 'devise_link'
  %br

  - if user_signed_in?
    = link_to 'ログアウト', destroy_user_session_path, class: 'devise_link link_login'
  - else 
    = link_to 'ログイン', new_user_session_path, class: 'devise_link link_login'


  

app/views/timelines/show.html.haml
.container 
  .camera
    = link_to image_tag('カメラ.png'), new_post_path , class: 'camera_icon'
  .timeline_title
    %p TIMELINE
  .timeline_container
  = render 'commons/posts'

  = link_to '全ての投稿一覧へ', posts_path, class: 'devise_link'
  %br
  = link_to '人気投稿一覧へ', timelinelike_path, class: 'devise_link'
  %br

  - if user_signed_in?
    = link_to 'ログアウト', destroy_user_session_path, class: 'devise_link link_login'
  - else 
    = link_to 'ログイン', new_user_session_path, class: 'devise_link link_login'